### ISSUE TITLE
New bug - AxiosError from commit 637ac9e (22 hours ago)

### ISSUE THREAD

**Issue by IzzyWorks** [alexandre-k/square-booking-app#5]
When logged in, clicking MyBookings - receive error "Location error. Unable to retrieve current location"

Console:

AxiosError {
message: 'Request failed with status code 404', 
name: 'AxiosError', 
code: 'ERR_BAD_REQUEST', 
...

**Comment by alexandre-k** [comment]
Thank you, I will look into that. At the moment the error isn't correct and it is due to a rate limit of the API.
As far as I have checked the API docs, there is no way at the moment to get a list of bookings from a customer, so I will have to do that locally and / or figure out  a way to do that with the API available.
